version: '3.5'

services:
  plania-api:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: plania-api
    ports:
      - 8068:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
