version: '3.8'

services:
  gemini-engine:
    container_name: gemini-engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
